name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lerna-version: [3.2.0, 4.0.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: |
          npm ci
          npm run build --if-present
      - name: Install lerna ${{ matrix.lerna-version }}
        run: npm install --no-save lerna@${{ matrix.lerna-version }}
      - name: Integration test
        run: npm exec jest --no-coverage integration

  without-lerna:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: |
          npm ci
          npm run build --if-present
      - name: Uninstall lerna
        run: npm rm --no-save lerna
      - name: Integration test
        run: npm exec jest --no-coverage integration
